version: '3.8'

volumes:
  pg-data3: {}
  bitbucket-data: {}

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: "15"

services:
  postgres3:
    container_name: postgres3
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: bitbucket
      POSTGRES_DB: bitbucket
      POSTGRES_PASSWORD: ocsg1234
    volumes:
     - pg-data3:/var/lib/postgresql/data/
    logging: *default-logging

  bitbucket:
    container_name: bitbucket
    image: atlassian/bitbucket-server:7.13.0
    restart: always
    environment:
      - SERVER_PROXY_NAME=${BUCKET_DOMAIN_NAME}
      - SERVER_PROXY_PORT=80
      - SERVER_SCHEME=https
      - SERVER_SECURE=true
      - JDBC_DRIVER=org.postgresql.Driver
      - JDBC_USER=bitbucket
      - JDBC_PASSWORD=ocsg1234
      - JDBC_URL=jdbc:postgresql://postgres3:5432/bitbucket
      - JVM_SUPPORT_RECOMMENDED_ARGS=-javaagent:/atlassian-agent.jar
    volumes:
      - ./atlassian-agent.jar:/atlassian-agent.jar
      - bitbucket-data:/var/atlassian/application-data/bitbucket/
    depends_on:
      - postgres3
    logging: *default-logging

